services:
  - type: web
    name: scitech-activity-calendar
    env: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --threads 4 --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: scitech-db
          property: connectionString

databases:
  - name: scitech-db
    databaseName: scitech
    user: scitech
    region: singapore
